### ISSUE TITLE
Create a query generator for repo popularity

### ISSUE THREAD

**Issue by tompscanlan** [tompscanlan/github-matchmaker#12]
See #5 for language service.  

Add a new service for getting a list of popular repositories to search

input: ">100"
output: query: "repo:one_project repo:two_project"

**Comment by s-rusev** [comment]
We can use the filter by stars repo here - ?q=stars:>100 or a range - 500..1000

**Comment by tompscanlan** [comment]
an alternative would be to search by comments.  This same service can be duplicated and used for searching github for arbitrary terms, and limiting the results of of our search to that set of repos.
