### ISSUE TITLE
create "pain" level service

### ISSUE THREAD

**Issue by tompscanlan** [tompscanlan/github-matchmaker#18]
Should try to create a query that is good at identifying "high" pain issues.  Should take a "high" setting at least.  A medium and low might be nice to have

**Comment by tompscanlan** [comment]
related to 1fc87298708409cab35a6ae115ad26cab27f12c4

**Comment by s-rusev** [comment]
Done in 1fc87298708409cab35a6ae115ad26cab27f12c4
Fixed the bug with the comments range.
