### ISSUE TITLE
UI should allow list of service backends to query

### ISSUE THREAD

**Issue by tompscanlan** [tompscanlan/github-matchmaker#2]
As an operator of the UI I want to be able to add a list of service urls to call with the preferences as seed input.  I expect the service to assemble results from each service into the final github query. It is okay to require a restart of the UI service after changing the backends.

**Comment by s-rusev** [comment]
For now we have linked the UI with the language service:
- python query-services\language\app.py 

And when querying it like http://localhost:5001/v1/language?seed=Java the service 
{ "query": "language:java" } 
which then will be appended to the query which we send to the Github api - "?q=language:java"

**Comment by s-rusev** [comment]
Added also "pain" backend service.

For now closing this - if we need to add new backend services they only need to be added to data.service.ts and be called with the proper seeds.
