### ISSUE TITLE
query service for language preference

### ISSUE THREAD

**Issue by tompscanlan** [tompscanlan/github-matchmaker#5]

**Comment by s-rusev** [comment]
Adding the query generation ideas from the README:

- language. seed=perl might yield query=lang:perl
- repository visibility. seed=low might yeild query=comments>10
- level of pain of the issue. seed=high might yield query=comments>30 +1 in:comments
- available time commitment, or difficulty of the fix. seed=low might yield query="not hard" in:comments or easy in:comments

For now the issues that are provided are with direct selection of the query terms - meaning we specify the query values like this:
q=type:issue state:open language:javascript author:s-rusev "some comment"  in:body comments:1 sort:reactions stars:1 

Useful links:
- https://help.github.com/articles/searching-issues-and-pull-requests/
- https://help.github.com/articles/understanding-the-search-syntax/

**Comment by tompscanlan** [comment]
Fixed
